'use strict';
const fs=require('fs'),path=require('path');
const {installFakeCaches,callWorker}=require('./cf_test_lib.cjs');
const root=path.resolve(__dirname,'..');
const tests=[];const add=(n,c,d='')=>tests.push({name:n,ok:!!c,detail:String(d||'')});
function upbitRows(n=200,{tf=60}={}){const ms=tf==='day'?86400000:Number(tf)*60000,out=[];for(let i=0;i<n;i++){const ts=1699999980000+i*ms,p=1000+i;out.push({timestamp:ts+37000,candle_date_time_utc:new Date(ts).toISOString().slice(0,19),opening_price:p,high_price:p+10,low_price:p-10,trade_price:p+3,candle_acc_trade_volume:50+i})}return out.reverse()}
(async()=>{
  const originalFetch=global.fetch;installFakeCaches();let calls=[];
  try{
    global.fetch=async(url,opt)=>{calls.push({url:String(url),opt});const u=new URL(String(url)),count=Math.max(1,Number(u.searchParams.get('count')||200)),tf=u.pathname.includes('/days')?'day':u.pathname.split('/').pop();return new Response(JSON.stringify(upbitRows(count,{tf})),{status:200,headers:{'content-type':'application/json'}})};
    let r=await callWorker(root,{method:'POST',ip:'10.0.1.1'});add('POST rejected',r.status===405,r.status);
    r=await callWorker(root,{query:{market:'bad',tf:'60',count:'200'},ip:'10.0.1.2'});add('invalid market 400',r.status===400,r.status);
    r=await callWorker(root,{query:{market:'KRW-BTC',tf:'2',count:'200'},ip:'10.0.1.3'});add('invalid timeframe 400',r.status===400,r.status);
    calls=[];r=await callWorker(root,{query:{market:'KRW-BTC',tf:'60',count:'1'},ip:'10.0.2.1'});add('minute 60 success',r.status===200,r.status);add('count min clamps 60',r.body.candles.length===60,r.body.candles.length);add('fixed HTTPS Upbit host',calls[0]?.url.startsWith('https://api.upbit.com/v1/candles/minutes/60?'),calls[0]?.url);add('market encoded',calls[0]?.url.includes('market=KRW-BTC'),calls[0]?.url);add('count 60 upstream',calls[0]?.url.includes('count=60'),calls[0]?.url);add('response source',r.body.source==='UPBIT PUBLIC API',r.body.source);add('response chronological',r.body.candles[0].t<r.body.candles.at(-1).t);add('canonical candle open timestamp',r.body.candles[0].t%60000===0,r.body.candles[0].t);add('OHLCV numeric',Object.values(r.body.candles[0]).every(Number.isFinite));add('content type json',String(r.headers['content-type']).includes('application/json'));add('cache-control no-store',r.headers['cache-control']==='no-store');
    calls=[];r=await callWorker(root,{query:{market:'KRW-ETH',tf:'240',count:'999'},ip:'10.0.2.2'});add('count max clamps 200',r.body.candles.length===200,r.body.candles.length);add('240 path',calls[0]?.url.includes('/minutes/240?'),calls[0]?.url);add('count 200 upstream',calls[0]?.url.includes('count=200'),calls[0]?.url);
    calls=[];r=await callWorker(root,{query:{market:'KRW-XRP',tf:'day',count:'160'},ip:'10.0.2.3'});add('day success',r.status===200);add('day path',calls[0]?.url.includes('/v1/candles/days?'),calls[0]?.url);add('day count 160',r.body.candles.length===160,r.body.candles.length);
    calls=[];await callWorker(root,{query:{market:'KRW-SOL',tf:'60',count:'160'},ip:'10.0.2.4'});const first=calls.length;r=await callWorker(root,{query:{market:'KRW-SOL',tf:'60',count:'160'},ip:'10.0.2.5'});add('Cloudflare cache avoids refetch',calls.length===first,calls.length);add('Cloudflare cache source',r.body.source==='UPBIT CACHE',r.body.source);
    let n=0;calls=[];global.fetch=async(url,opt)=>{calls.push({url:String(url),opt});n++;if(n<3)return new Response('{}',{status:503});return new Response(JSON.stringify(upbitRows(160,{tf:240})),{status:200,headers:{'content-type':'application/json'}})};
    r=await callWorker(root,{query:{market:'KRW-DOGE',tf:'240',count:'160'},ip:'10.0.3.1'});add('retry succeeds on third',r.status===200&&n===3,`status=${r.status}, calls=${n}`);add('retry same fixed host',calls.every(x=>x.url.startsWith('https://api.upbit.com/')));
    n=0;global.fetch=async()=>{n++;return new Response('{}',{status:500})};r=await callWorker(root,{query:{market:'KRW-BTC',tf:'30',count:'160'},ip:'10.0.3.2'});add('upstream failure 502',r.status===502,r.status);add('upstream retry 3 attempts',n===3,n);add('error shape',r.body.error==='upstream_unavailable'&&typeof r.body.message==='string');
    r=await callWorker(root,{pathName:'/api/health',ip:'10.0.4.1'});add('health 200',r.status===200&&r.body.ok===true);add('health version 15.31.29',r.body.version==='15.31.29',r.body.version);add('health Cloudflare platform',r.body.platform==='cloudflare-workers',r.body.platform);add('health no paid/order',r.body.paidApiRequired===false&&r.body.orderApiEnabled===false);
    r=await callWorker(root,{pathName:'/api/version',ip:'10.0.4.2'});add('version endpoint',r.status===200&&r.body.version==='15.31.29'&&r.body.release==='V15.31.29',JSON.stringify(r.body));add('version Cloudflare platform',r.body.platform==='cloudflare-workers');
    r=await callWorker(root,{pathName:'/api/unknown',ip:'10.0.4.3'});add('unknown API 404',r.status===404&&r.body.error==='not_found',JSON.stringify(r.body));
    global.fetch=async()=>new Response(JSON.stringify(upbitRows(60,{tf:15})),{status:200,headers:{'content-type':'application/json'}});let rr;for(let i=1;i<=61;i++)rr=await callWorker(root,{query:{market:'KRW-BTC',tf:'15',count:'60'},headers:{'CF-Connecting-IP':'203.0.113.77'},ip:null});add('61st request rate limited',rr.status===429,rr.status);add('429 response shape',rr.body.error==='rate_limited'&&rr.body.retryAfterSeconds===60,JSON.stringify(rr.body));add('Retry-After header',rr.headers['retry-after']==='60',rr.headers['retry-after']);
    add('API security X-Content-Type-Options',r.headers['x-content-type-options']==='nosniff',r.headers['x-content-type-options']);
  }finally{global.fetch=originalFetch}
  const pass=tests.filter(x=>x.ok).length,total=tests.length,result={version:'15.31.29',platform:'cloudflare-workers',pass,total,failed:tests.filter(x=>!x.ok),tests,generatedAt:new Date().toISOString()};fs.mkdirSync(path.join(root,'docs'),{recursive:true});fs.writeFileSync(path.join(root,'docs','MOBILE_ONLY_API_E2E.json'),JSON.stringify(result,null,2));console.log(`RESULT ${pass}/${total} PASS`);if(pass!==total){for(const x of result.failed)console.error('FAIL',x.name,x.detail);process.exit(1)}
})().catch(e=>{console.error(e);process.exit(1)});
