'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.resolve(__dirname,'..'),PORT=9341,profile='/tmp/ca_v153121_stress';fs.rmSync(profile,{recursive:true,force:true});
const chrome=cp.spawn('/usr/bin/chromium',['--headless=new','--no-sandbox','--disable-gpu',`--remote-debugging-port=${PORT}`,`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','ignore']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
class CDP{constructor(url){this.ws=new WebSocket(url);this.id=0;this.p=new Map();this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const q=this.p.get(m.id);if(q){this.p.delete(m.id);m.error?q.reject(new Error(m.error.message)):q.resolve(m.result)}}}}ready(){return this.ws.readyState===1?Promise.resolve():new Promise((r,j)=>{this.ws.onopen=r;this.ws.onerror=j})}call(method,params={}){return new Promise((r,j)=>{const id=++this.id;this.p.set(id,{resolve:r,reject:j});this.ws.send(JSON.stringify({id,method,params}))})}close(){this.ws.close()}}
(async()=>{let c;try{for(let i=0;i<50;i++){try{const pages=await(await fetch(`http://127.0.0.1:${PORT}/json`)).json();if(pages[0]){c=new CDP(pages[0].webSocketDebuggerUrl);await c.ready();break}}catch{}await sleep(100)}if(!c)throw new Error('CDP unavailable');await c.call('Page.enable');await c.call('Runtime.enable');const frameId=(await c.call('Page.getFrameTree')).frameTree.frame.id;let html=fs.readFileSync(path.join(root,'public','index.html'),'utf8').replace(/<link rel="stylesheet" href="\.\/styles\.css">/,'').replace(/<script src="\.\/user-data-store\.js"><\/script>/,'').replace(/<script src="\.\/user-data-store\.js"><\/script>/,'').replace(/<script src="\.\/app\.js"><\/script>/,'');html=html.replace('</head>',`<style>${fs.readFileSync(path.join(root,'public','styles.css'),'utf8')}</style></head>`);await c.call('Page.setDocumentContent',{frameId,html});await c.call('Runtime.evaluate',{expression:'window.__CA_FORCE_DEMO__=true;'});await c.call('Runtime.evaluate',{expression:fs.readFileSync(path.join(root,'public','user-data-store.js'),'utf8')});await c.call('Runtime.evaluate',{expression:fs.readFileSync(path.join(root,'public','app.js'),'utf8')});await c.call('Runtime.evaluate',{expression:'window.__CA_TEST__.boot()',awaitPromise:true});
const expr=`(()=>{const T=window.__CA_TEST__,out={normalization:{total:5000,fail:0},integrity:{total:1000,fail:0},scenario:{total:500,fail:0},summary:{total:500,fail:0},entry:{total:500,fail:0},edge:{total:500,fail:0},regime:{total:500,fail:0},calibration:{total:200,fail:0},details:[]};let seed=153117;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
const raw=[];for(let i=0;i<5000;i++){const good=rnd()>.18,t=1700000000000+i*60000,o=100+rnd()*100,c=o*(.98+rnd()*.04),h=Math.max(o,c)*(1+rnd()*.02),l=Math.min(o,c)*(1-rnd()*.02),v=rnd()*1000;raw.push(good?{t,o,h,l,c,v}:{t:i%3?0:t,o:i%5?-1:o,h,l,c,v:-1})}const norm=T.normalizeCandleRows(raw);if(norm.some(r=>![r.t,r.o,r.h,r.l,r.c,r.v].every(Number.isFinite)||r.t<=0||r.o<=0||r.h<Math.max(r.o,r.c)||r.l>Math.min(r.o,r.c)||r.v<0))out.normalization.fail++;
const baseInt=T.demoCandles('KRW-BTC','60',200);for(let z=0;z<1000;z++){const d=baseInt.map(x=>({...x}));if(z%7===0)d[80]={...d[80],t:d[79].t};else if(z%11===0)d[90]={...d[90],c:d[89].c*1.5,h:d[89].c*1.51,l:d[89].c*.99};const g=T.dataIntegrityGate(d,'60');if(z%7===0){if(g.level!=='BLOCKED')out.integrity.fail++}else if(!['READY','CAUTION','BLOCKED'].includes(g.level)||!Array.isArray(g.rows))out.integrity.fail++}
for(let z=0;z<200;z++){const a=[];for(let i=0;i<24;i++){const high=i>=12;a.push({resolved:true,excluded:false,confidence:high?.84:.68,hit:high?(i%3!==0):(i%2===0)})}const c=T.confidenceCalibration(a);if(!c||c.samples!==24||!['CALIBRATED','OVERCONFIDENT','MISCALIBRATED'].includes(c.status))out.calibration.fail++}
for(let k=0;k<500;k++){try{const market=['KRW-BTC','KRW-ETH','KRW-XRP','KRW-SOL','KRW-DOGE'][k%5],tf=['60','240','day'][k%3],rows=T.demoCandles(market,tf,200).map((x,i)=>{const f=1+(rnd()-.5)*.01*Math.sin((i+k)/11);return {...x,o:x.o*f,h:x.h*f,l:x.l*f,c:x.c*f,v:x.v*(.8+rnd()*.4)}}),q=T.qualityAssessment(rows),s=T.computeSignal(rows),bt=T.backtest(rows),learn=k%4===0?[{resolved:true,hit:true,return:.02},{resolved:true,hit:false,return:-.01},{resolved:true,hit:true,return:.015}]:[],v=T.finalValidation(rows,s,q,bt,learn),sum=T.buildDecisionSummary(s,q,v);const eq=T.entryQuality(rows,s),sp=T.scenarioPlanner(rows,s,eq,v),edge=bt.edge;const ok=Number.isFinite(s.score)&&s.score>=0&&s.score<=100&&Number.isFinite(s.rsi)&&Number.isFinite(s.atrPct)&&Number.isFinite(bt.pf)&&Number.isFinite(bt.sharpe)&&Number.isFinite(v.reliability)&&v.reliability>=0&&v.reliability<=1&&['LOW','MEDIUM','HIGH'].includes(T.confidenceBand(v.reliability));if(!ok){out.scenario.fail++;if(out.details.length<10)out.details.push({k,s:s.score,r:v.reliability})}if(!Array.isArray(sum)||sum.length!==3||sum.some(x=>x.length!==2||!x[1]))out.summary.fail++;if(!eq||!['GOOD','WAIT','CHASE RISK'].includes(eq.label)||!Number.isFinite(eq.score)||!sp||!['BULL','NEUTRAL','BEAR'].includes(sp.current))out.entry.fail++;if(!edge||!['POSITIVE EDGE','DEFENSIVE EDGE','NO CLEAR EDGE','INSUFFICIENT'].includes(edge.label)||!Number.isFinite(edge.returnEdge)||!Number.isFinite(edge.mddEdge)||!Number.isFinite(edge.sharpeEdge))out.edge.fail++;if(!bt.regimeEdges||Object.keys(bt.regimeEdges).length!==5||Object.values(bt.regimeEdges).some(x=>!['POSITIVE EDGE','DEFENSIVE EDGE','NO CLEAR EDGE','INSUFFICIENT'].includes(x.label)))out.regime.fail++}catch(e){out.scenario.fail++;if(out.details.length<10)out.details.push({k,error:e.message})}}
return out})()`;
const r=await c.call('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);const x=r.result.value;const tests=[{name:'OHLCV normalization fuzz 5000',ok:x.normalization.fail===0,detail:String(x.normalization.fail)},{name:'data integrity stress 1000',ok:x.integrity.fail===0,detail:String(x.integrity.fail)},{name:'analysis/backtest/final validation stress 500',ok:x.scenario.fail===0,detail:String(x.scenario.fail)},{name:'decision summary stress 500',ok:x.summary.fail===0,detail:String(x.summary.fail)},{name:'entry/scenario planner stress 500',ok:x.entry.fail===0,detail:String(x.entry.fail)},{name:'strategy edge stress 500',ok:x.edge.fail===0,detail:String(x.edge.fail)},{name:'regime edge stress 500',ok:x.regime.fail===0,detail:String(x.regime.fail)},{name:'confidence calibration stress 200',ok:x.calibration.fail===0,detail:String(x.calibration.fail)}],pass=tests.filter(t=>t.ok).length,total=tests.length,result={version:'15.31.29',pass,total,tests,raw:x,generatedAt:new Date().toISOString()};fs.writeFileSync(path.join(root,'docs','MOBILE_ONLY_LOGIC_STRESS.json'),JSON.stringify(result,null,2));console.log(`RESULT ${pass}/${total} PASS`);if(pass!==total)process.exitCode=1;
}catch(e){console.error(e);process.exitCode=1}finally{try{c?.close()}catch{}chrome.kill('SIGKILL')}})();
