'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');let pass=0,fail=0;const tests=[];
const check=(n,c,d='')=>{tests.push({name:n,ok:!!c,detail:String(d||'')});(c?console.log:console.error)(c?'PASS':'FAIL',n,d);c?pass++:fail++};
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const files=['public/index.html','public/styles.css','public/user-data-store.js','public/app.js','public/manifest.json','public/sw.js','public/_headers','public/icons/icon-192.png','public/icons/icon-512.png','src/worker.mjs','wrangler.jsonc','package.json','package-lock.json'];
for(const f of files)check(`exists ${f}`,fs.existsSync(path.join(root,f)));
const storageLayer=read('public/user-data-store.js');
const textual=files.filter(f=>!f.endsWith('.png')),all=textual.map(read).join('\n'),index=read('public/index.html'),app=read('public/app.js'),css=read('public/styles.css'),sw=read('public/sw.js'),worker=read('src/worker.mjs'),headers=read('public/_headers'),cfg=JSON.parse(read('wrangler.jsonc'));
check('runtime version 15.31.29',all.includes('15.31.29'));
check('Korean brand visible',index.includes('코인나침반')&&read('public/manifest.json').includes('코인나침반'));
check('stable internal namespace after migration',app.includes("STORAGE_NS='crypto_analyzer_mobile'"));
check('dedicated UserDataStore layer',storageLayer.includes('class LocalUserDataStore')&&app.includes('createLocalUserDataStore'));
check('app has no direct localStorage',!/window\.localStorage|\blocalStorage\s*\./.test(app));
check('offline-first storage capability',storageLayer.includes("driver:'local'")&&storageLayer.includes('offlineFirst:true')&&storageLayer.includes('cloudSync:false'));
check('future sync snapshot seam',storageLayer.includes('exportSnapshot()')&&storageLayer.includes('importSnapshot('));
check('storage layer loaded before app',index.indexOf('user-data-store.js')>=0&&index.indexOf('user-data-store.js')<index.indexOf('app.js'));
check('no login UI introduced',!/type=[\"\']password[\"\']|로그인|회원가입/.test(index));
check('Cloudflare Worker main',cfg.main==='src/worker.mjs');
check('Cloudflare static assets',cfg.assets?.directory==='./public'&&cfg.assets?.binding==='ASSETS');
check('API worker-first only',Array.isArray(cfg.assets?.run_worker_first)&&cfg.assets.run_worker_first.length===1&&cfg.assets.run_worker_first[0]==='/api/*');
check('no Vercel config',!fs.existsSync(path.join(root,'vercel.json')));
check('no legacy Vercel api directory',!fs.existsSync(path.join(root,'api')));
check('Cloudflare Cache API',worker.includes('caches.default')&&worker.includes('cache.match')&&worker.includes('cache.put'));
check('cache is optimization fail-open',worker.includes('Cache is an optimization only')&&worker.includes('catch'));
check('no paid Cloudflare data binding',!/(D1Database|DurableObject|R2Bucket|\bKV\b)/.test(worker+JSON.stringify(cfg)));
check('no order/account endpoint',!/placeOrder|createOrder|\/v1\/(orders|accounts|withdraw|deposit)/i.test(worker));
check('no obvious secret',!/(sk-[A-Za-z0-9_-]{20,}|eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{10,})/.test(all));
check('fixed Upbit host',worker.includes("const FIXED_BASE = 'https://api.upbit.com'"));
check('canonical candle open time',worker.includes('candle_date_time_utc')&&worker.includes('Date.parse'));
check('server candle integrity validation',worker.includes("throw new Error('Invalid Upbit candle payload')")&&worker.includes('x.h >= Math.max(x.o, x.c)'));
check('static CSP self connect',headers.includes("connect-src 'self'"));
for(const h of ['Strict-Transport-Security','X-Content-Type-Options','X-Frame-Options','Referrer-Policy','Permissions-Policy','Cross-Origin-Opener-Policy','Content-Security-Policy'])check(`static security header ${h}`,headers.includes(h));
check('API security headers',worker.includes("'x-content-type-options': 'nosniff'")&&worker.includes("'x-frame-options': 'DENY'"));
check('mobile viewport',index.includes('viewport-fit=cover'));
check('4 bottom tabs',(index.match(/class="tab(?: |")/g)||[]).length===4&&index.includes('bottomNav')&&!index.includes('data-tab="status"'));
check('status pane removed',!index.includes('pane-status'));
check('management in settings',index.includes('healthCheckBtn')&&index.includes('lastBackupText')&&index.includes('pane-settings'));
check('home management rows removed',!index.includes('<b>앱 상태 검사</b>')&&!index.includes('<b>백업 상태</b>'));
check('conditional home warning',index.includes('homeAlertBanner')&&app.includes('dot.hidden=!show'));
const homeHtml=index.slice(index.indexOf('id="pane-home"'),index.indexOf('id="pane-analysis"'));
check('headline-first home dashboard',homeHtml.includes('homeHeadlineCard')&&homeHtml.includes('homeHeadline')&&homeHtml.includes('homeDeck')&&homeHtml.includes('homeReasonDetails')&&homeHtml.includes('summaryList')&&app.includes('refreshHomeSummary'));
check('Forward Learning hidden from home',!homeHtml.includes('Forward Learning')&&index.includes('실전 결과 학습 (Forward Learning)'));
check('progressive disclosure reason',homeHtml.includes('<details class="homeReasonDetails"')&&homeHtml.includes('판단 근거 확인'));
check('first-run onboarding',index.includes('onboardingOverlay')&&app.includes('completeOnboarding')&&app.includes('showOnboardingIfNeeded'));
check('favorites profile',index.includes('favoriteGrid')&&app.includes('sanitizeFavorites')&&app.includes('saveUiPreferences'));
check('last selection memory',app.includes('lastMarket')&&app.includes('lastTf')&&app.includes('lastTab'));
check('update status UX',index.includes('updateStatus')&&app.includes('updatedFrom'));
check('removed status tab migration',app.includes("x.lastTab==='status'")&&app.includes("x.lastTab='settings'"));
check('backup status UX',index.includes('lastBackupText')&&app.includes('BACKUP_META_KEY')&&app.includes('lastExportAt'));
check('readiness UX',index.includes('readinessOverall')&&index.includes('homeAlertBanner')&&app.includes('renderReadiness')&&app.includes('backupDue'));
check('decision safety gate',index.includes('decisionSafetyCard')&&app.includes('safetyLevel')&&app.includes('blockedSource'));
check('entry quality gate',index.includes('entryQualityValue')&&app.includes('function entryQuality')&&app.includes("entry.label==='CHASE RISK'"));
check('scenario planner',index.includes('scenarioPlanner')&&app.includes('function scenarioPlanner')&&app.includes('current=signal.score>=60'));
check('strategy edge vs buy hold',index.includes('btBuyHold')&&index.includes('btEdgeOverall')&&app.includes('function benchmarkMetrics')&&app.includes('function strategyEdge'));
check('conservative cost assumption',app.includes('SIM_ROUNDTRIP_COST=0.0015')&&index.includes('왕복 0.15%'));
check('safe snapshot recovery',app.includes('SNAPSHOT_KEY')&&app.includes('saveSafeSnapshot')&&app.includes('getSafeSnapshot'));
check('forward maturity gate',app.includes("maturity=r.length>=50?'MATURE'")&&index.includes('flMaturity'));
check('temporal stability',app.includes('temporalStability')&&index.includes('btTemporal'));
check('data integrity gate',app.includes('function dataIntegrityGate')&&app.includes('DATA_INTEGRITY_BLOCKED')&&index.includes('데이터 무결성'));
check('confidence calibration',app.includes('function confidenceCalibration')&&index.includes('flCalibration')&&index.includes('calibrationBands'));
check('regime edge analysis',app.includes('function regimeEdgeAnalysis')&&index.includes('regimeEdgeList')&&app.includes('currentRegimeEdge'));
check('one tap health check',app.includes('function healthCheck')&&index.includes('healthCheckBtn')&&index.includes('healthCheckList'));
check('forward records capture confidence',app.includes('confidence:a.validation.reliability')&&app.includes('regime:a.regime'));
check('backup schema v2',app.includes('schemaVersion:2')&&app.includes('uiProfile:loadUiProfile()'));
check('old backup compatible',app.includes('![1,2].includes(obj.schemaVersion)'));
check('font accessibility',index.includes('fontScaleSelect')&&css.includes('body.font-large')&&app.includes('applyFontScale'));
check('no background polling',!/\bsetInterval\s*\(/.test(app));
check('44px touch minimum',/min-height:44px/.test(css));
check('mobile summary touch card',css.includes('.summaryCard')&&app.includes("closest('.summaryCard')"));
check('legacy v16 migration',app.includes('crypto_analyzer_v15_31_16'));
check('data-state transparency',index.includes('dataStateCard')&&app.includes('freshnessMeta'));
check('confidence disclaimer',index.includes('수익확률이 아닙니다'));
check('notification default off',/decisionAlerts:false/.test(app));
check('service worker notification',app.includes('showNotification'));
check('SW cache v16',sw.includes('static-v16'));
check('SW precaches storage layer',sw.includes("'./user-data-store.js'"));
check('SW API bypass',sw.includes("startsWith('/api/')"));
check('PWA icons',index.includes('apple-touch-icon')&&read('public/manifest.json').includes('192x192')&&read('public/manifest.json').includes('512x512'));
const pkg=JSON.parse(read('package.json')),lock=JSON.parse(read('package-lock.json')),man=JSON.parse(read('public/manifest.json'));
check('package version',pkg.version==='15.31.29'&&lock.version==='15.31.29');
check('manifest version',man.version==='15.31.29'&&man.display==='standalone');
check('Cloudflare deploy scripts',pkg.scripts?.dev?.includes('wrangler')&&pkg.scripts?.deploy?.includes('wrangler'));
check('easy language home labels',index.includes('진입 위치')&&index.includes('시장 흐름')&&index.includes('전략 우위'));
check('technical labels retained in detail',index.includes('Entry Quality')&&index.includes('Scenario')&&index.includes('Strategy Edge'));
check('easy language mapping functions',app.includes('function easyEntryLabel')&&app.includes('function easyScenarioLabel')&&app.includes('function easyEdgeLabel')&&app.includes('function easyDataLabel'));
check('cross-context outage guard',app.includes('priorAnalysis.market===market&&priorAnalysis.tf===tf')&&app.includes('sameContext'));
check('cross-context stale UI reset',app.includes('function renderUnavailableAnalysis')&&app.includes('이전 다른 코인·시간대 결과는 표시하지 않습니다.'));
check('no runtime dependencies',!pkg.dependencies&&!pkg.devDependencies);
check('no eval/new Function',!/(\beval\s*\(|new\s+Function\s*\()/.test(all));
check('worker pure web runtime',!worker.includes('require(')&&!worker.includes('process.')&&!worker.includes('Buffer.'));
check('assets directory excludes control code',cfg.assets.directory==='./public'&&!files.some(f=>f.startsWith('public/src/')));
fs.mkdirSync(path.join(root,'docs'),{recursive:true});fs.writeFileSync(path.join(root,'docs','MOBILE_ONLY_STATIC_AUDIT.json'),JSON.stringify({version:'15.31.29',platform:'cloudflare-workers',pass,total:pass+fail,failed:tests.filter(x=>!x.ok),tests,generatedAt:new Date().toISOString()},null,2));console.log(`RESULT ${pass}/${pass+fail} PASS`);process.exit(fail?1:0);
